### ISSUE TITLE
Outdated versions in Java tooling documentation  

### ISSUE THREAD

**Issue by schabdo** [eclipse-esmf/eclipse-esmf.github.io#22]
Looking at the [documentation](https://eclipse-esmf.github.io/esmf-developer-guide/tooling-guide/java-aspect-tooling.html) for Java all depicted versions are outdated e.g.

```xml
<dependency>
    <groupId>org.eclipse.esmf</groupId>
    <artifactId>esmf-aspect-model-resolver</artifactId>
    <version>2.3.2</version>
</dependency>
``` 

Newest version available: https://central.sonatype.com/artifact/org.eclipse.esmf/esmf-aspect-model-resolver/2.4.1

**Comment by chris-volk** [comment]
Already fixed, see https://eclipse-esmf.github.io/esmf-developer-guide/tooling-guide/java-aspect-tooling.html ,  

> <version>2.4.1</version>
